#!/usr/bin/env bash
# A script that gives information about a file

file="School"

if [ -e "$file" ]; then
	echo "School file exist"
	if [ -s "$file" ]; then
		echo "School file not empty"
	else
		echo "School file is empty"
	fi
	if [ -f "$file" ]; then
		echo "School is a regular file"
	fi
else
	echo "School file does not exist"
fi
