#!/usr/bin/env bash
# A script that gives information about a file

file="school"
if [ -e "school" ]; then
	echo "school file exist"
	if [ -s "$file" ]; then
		echo "school file not empty"
	else
		echo "school file is empty"
	fi
	if [ -f "$file" ]; then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
